### ISSUE TITLE
add checks

### ISSUE THREAD

**Issue by wh1te909** [amidaware/community-scripts#2]
add github actions and checks that were removed from main repo here

**Comment by wh1te909** [comment]
https://github.com/wh1te909/tacticalrmm/commit/ef1afc99c659d5df2aa2a8537d3b722de38cad82

**Comment by sadnub** [comment]
Just added a GH action to run the json file tests. just using pytest and reworked the old tests a bit

**Comment by wh1te909** [comment]
nice!!!!!
