### ISSUE TITLE
speed test URL down

### ISSUE THREAD

**Issue by bbrendon** [amidaware/community-scripts#238]
I guess multiple options should be listed.

https://github.com/amidaware/community-scripts/blob/4d653414d8859e4bde2ff8ae4c07d9153cf5a215/scripts/Win_Speedtest.ps1#L8C17-L8C54

**Comment by bbrendon** [comment]
fixed https://github.com/amidaware/community-scripts/pull/239

**Comment by wh1te909** [comment]
Thanks, I removed the dead link completely and just kept the one you added but left it an array so more can be added later if needed.
