### ISSUE TITLE
Modify tests to check for duplicate entries

### ISSUE THREAD

**Issue by silversword411** [amidaware/community-scripts#55]
See:

https://github.com/amidaware/community-scripts/blob/eaf62b855c3994de5296e40d683fc803f0528dd0/community_scripts.json#L578

and 

https://github.com/amidaware/community-scripts/blob/eaf62b855c3994de5296e40d683fc803f0528dd0/community_scripts.json#L582

Should probably make sure all fields aren't duplicated

**Comment by silversword411** [comment]
@wh1te909 ...did we try doing this already and couldn't get it to work?

**Comment by wh1te909** [comment]
python does not allow dicts to have duplicate keys so when it's imported, the duplicate is removed automatically, but this can lead to unexpected behavior because we won't know which line was removed. I have just addded a check to catch duplicates

**Comment by wh1te909** [comment]
https://github.com/amidaware/community-scripts/runs/7028877647?check_suite_focus=true shows it catching it
